---
# Inventory for rollback demonstration
all:
  children:
    network_devices:
      children:
        production_routers:
          hosts:
            prod-router-01:
              ansible_host: 192.168.10.1
              device_type: cisco_ios
              criticality: high
            prod-router-02:
              ansible_host: 192.168.10.2
              device_type: cisco_ios
              criticality: high
        
        production_switches:
          hosts:
            prod-switch-01:
              ansible_host: 192.168.10.11
              device_type: cisco_ios
              criticality: medium
            prod-switch-02:
              ansible_host: 192.168.10.12
              device_type: cisco_ios
              criticality: medium
            prod-switch-03:
              ansible_host: 192.168.10.13
              device_type: cisco_ios
              criticality: medium
  
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_user: admin
    ansible_password: "{{ vault_password }}"
    ansible_become: yes
    ansible_become_method: enable
