---
# Inventory for templated configurations based on device type and location
all:
  children:
    network_devices:
      children:
        core_routers:
          hosts:
            core-router-nyc-01:
              ansible_host: 10.10.1.1
              device_role: core
              location: nyc
              datacenter: dc1
            core-router-nyc-02:
              ansible_host: 10.10.1.2
              device_role: core
              location: nyc
              datacenter: dc1
        
        edge_routers:
          hosts:
            edge-router-london-01:
              ansible_host: 10.20.1.1
              device_role: edge
              location: london
              datacenter: dc2
            edge-router-tokyo-01:
              ansible_host: 10.30.1.1
              device_role: edge
              location: tokyo
              datacenter: dc3
        
        access_switches:
          hosts:
            access-switch-nyc-01:
              ansible_host: 10.10.2.1
              device_role: access
              location: nyc
              datacenter: dc1
              floor: 1
            access-switch-london-01:
              ansible_host: 10.20.2.1
              device_role: access
              location: london
              datacenter: dc2
              floor: 3
  
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_user: admin
    ansible_password: "{{ vault_password }}"
